version: '3.8'

services:
  app:
    build: .
    container_name: url-shortnr
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: "url-shortnr-redis"
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning


networks:
  app-network:

volumes:
  redis-data:
  grafana-data: