version: '3.8'

services:
  app:
    build: .
    container_name: url-shortnr
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    networks:
      - app-network

  redis:
    image: "redis:latest"
    container_name: "url-shortnr-redis"
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:

volumes:
  redis-data: